const COZY_CAT_ASSETS=Object.freeze({idle:'./assets/cat-idle.avif?v=22',happy:'./assets/cat-happy.avif?v=22',hungry:'./assets/cat-hungry.avif?v=22',sleep:'./assets/cat-sleep.avif?v=22',eat:'./assets/cat-eat.avif?v=22',celebrate:'./assets/cat-celebrate.avif?v=22'});
const COZY_CAT_STATE_CLASSES=Object.keys(COZY_CAT_ASSETS).map(n=>`state-${n}`);
let cozyCatActionTimer=0,cozyCatActionLocked=false,cozyCatCurrentState='';
function cozyCatReadNumber(k,f){const n=Number(localStorage.getItem(k));return Number.isFinite(n)?n:f}
function cozyCatInventory(){try{return{milk:0,chicken:0,cake:0,beef:0,...JSON.parse(localStorage.getItem('cozy9Inventory')||'{}')}}catch(_){return{milk:0,chicken:0,cake:0,beef:0}}}
function cozyCatBaseState(){const full=cozyCatReadNumber('cozy9Fullness',60),fish=cozyCatReadNumber('cozy9Fish',30);let sleeping=localStorage.getItem('cozy11CatSleeping')==='1';if(full<=28){localStorage.setItem('cozy11CatSleeping','0');return'hungry'}if(sleeping&&fish<=55){sleeping=false;localStorage.setItem('cozy11CatSleeping','0')}if(!sleeping&&fish>=75){sleeping=true;localStorage.setItem('cozy11CatSleeping','1')}return sleeping?'sleep':'idle'}
function cozyCatSetState(name){const img=document.getElementById('cat'),wrap=document.getElementById('catWrap');if(!img||!wrap||!COZY_CAT_ASSETS[name])return;cozyCatCurrentState=name;COZY_CAT_STATE_CLASSES.forEach(c=>wrap.classList.remove(c));wrap.classList.remove('mood-good','mood-mid','mood-low','mood-very-low');const mood=cozyCatReadNumber('cozy9Mood',80);wrap.classList.add(`state-${name}`,mood<20?'mood-very-low':mood<40?'mood-low':mood<70?'mood-mid':'mood-good');const wanted=COZY_CAT_ASSETS[name];if(img.getAttribute('src')!==wanted)img.setAttribute('src',wanted);img.dataset.catState=name}
function cozyCatSyncBase(){if(!cozyCatActionLocked)cozyCatSetState(cozyCatBaseState())}
function cozyCatPlay(name,duration=1500){clearTimeout(cozyCatActionTimer);cozyCatActionLocked=true;cozyCatSetState(name);cozyCatActionTimer=setTimeout(()=>{cozyCatActionLocked=false;cozyCatSyncBase()},duration)}
function cozyCatTodayKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function cozyCatEnsureStyles(){if(document.querySelector('link[data-cozy-cat-anim]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./cat-anim.css?v=23';l.dataset.cozyCatAnim='1';document.head.appendChild(l)}
function cozyCatPreload(){Object.values(COZY_CAT_ASSETS).forEach(src=>{const i=new Image();i.src=src})}
function cozyCatInit(){const img=document.getElementById('cat'),wrap=document.getElementById('catWrap');if(!img||!wrap)return;cozyCatEnsureStyles();cozyCatPreload();cozyCatSyncBase();new MutationObserver(()=>{const wanted=COZY_CAT_ASSETS[cozyCatCurrentState||cozyCatBaseState()];if(wanted&&img.getAttribute('src')!==wanted)img.setAttribute('src',wanted)}).observe(img,{attributes:true,attributeFilter:['src']});const targets=['moodNum','foodNum','fishNum'].map(id=>document.getElementById(id)).filter(Boolean);if(targets.length){const o=new MutationObserver(()=>setTimeout(cozyCatSyncBase,0));targets.forEach(el=>o.observe(el,{childList:true,subtree:true,characterData:true}))}document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;const f=t.closest('[data-feed]'),q=t.closest('#quickFeedBtn');if(f){const inv=cozyCatInventory();e.__cozyCanFeed=(inv[f.dataset.feed]||0)>0}else if(q)e.__cozyCanFeed=Object.values(cozyCatInventory()).some(v=>Number(v)>0);if(t.closest('#checkinBtn'))e.__cozyCanCheckin=localStorage.getItem('cozy10LastCheckin')!==cozyCatTodayKey()},true);document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;if(t.closest('#petBtn')||t.closest('#cat')){cozyCatPlay('happy',1450);return}if((t.closest('[data-feed]')||t.closest('#quickFeedBtn'))&&e.__cozyCanFeed){setTimeout(()=>cozyCatPlay('eat',1750),610);return}if(t.closest('#checkinBtn')&&e.__cozyCanCheckin)setTimeout(()=>cozyCatPlay('celebrate',1650),80)});const learned=document.getElementById('learnedCount');if(learned){let last=Number(learned.textContent)||0;new MutationObserver(()=>{const now=Number(learned.textContent)||0;if(last<20&&now===20)cozyCatPlay('celebrate',1700);last=now}).observe(learned,{childList:true,subtree:true,characterData:true})}const quiz=document.getElementById('quizScoreLabel');if(quiz){let done=false;new MutationObserver(()=>{const text=quiz.textContent.trim(),now=text.startsWith('完成')||text.startsWith('复习完成');if(now&&!done)cozyCatPlay('celebrate',1700);done=now}).observe(quiz,{childList:true,subtree:true,characterData:true})}window.addEventListener('storage',cozyCatSyncBase)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(cozyCatInit,0),{once:true});else setTimeout(cozyCatInit,0);
