(()=>{
const rows = [
['die Bedeutung','意义，重要性','Die Bedeutung guter Sprachkenntnisse wird oft unterschätzt.','校园'],
['die Entwicklung','发展，进程','Die technische Entwicklung verändert unseren Alltag.','图表'],
['die Gesellschaft','社会','In der modernen Gesellschaft spielt Bildung eine große Rolle.','讨论'],
['die Herausforderung','挑战','Ein Studium im Ausland ist für viele eine große Herausforderung.','校园'],
['die Möglichkeit','可能性，机会','Online-Kurse bieten neue Möglichkeiten zum Lernen.','讨论'],
['die Voraussetzung','前提，条件','Gute Sprachkenntnisse sind eine wichtige Voraussetzung für das Studium.','校园'],
['berücksichtigen','考虑，顾及','Bei der Planung muss man viele Faktoren berücksichtigen.','书面语'],
['zunehmen','增加，增长','Die Zahl der Studierenden nimmt jedes Jahr zu.','图表'],
['verringern','减少，降低','Neue Maßnahmen können die Kosten deutlich verringern.','图表'],
['sich auswirken auf','对……产生影响','Stress kann sich negativ auf die Gesundheit auswirken.','讨论'],
['die Maßnahme','措施','Die Stadt plant neue Maßnahmen zum Klimaschutz.','书面语'],
['verfügen über','拥有，具备','Viele Hochschulen verfügen über moderne Labore.','校园'],
['ermöglichen','使……成为可能','Digitale Medien ermöglichen flexibleres Lernen.','校园'],
['der Beitrag','贡献','Jeder kann einen kleinen Beitrag zum Umweltschutz leisten.','讨论'],
['sich eignen für','适合……','Diese Methode eignet sich gut für Gruppenarbeit.','校园'],
['nachhaltig','可持续的','Nachhaltige Lösungen werden immer wichtiger.','环保'],
['in Anspruch nehmen','占用；利用','Die Vorbereitung auf die Prüfung nimmt viel Zeit in Anspruch.','书面语'],
['stattfinden','举行，发生','Die Veranstaltung findet nächste Woche statt.','校园'],
['überwiegen','占优势，更多','In diesem Fall überwiegen die Vorteile.','讨论'],
['die Anforderung','要求','Die Anforderungen im Beruf sind sehr unterschiedlich.','职场'],
['die Fähigkeit','能力','Teamfähigkeit ist in vielen Berufen besonders wichtig.','职场'],
['die Forschung','研究','Die Universität investiert mehr Geld in die Forschung.','校园'],
['der Zusammenhang','联系，关联','Zwischen Schlaf und Leistung besteht ein enger Zusammenhang.','书面语'],
['der Anteil','比例，份额','Der Anteil erneuerbarer Energien ist gestiegen.','图表'],
['im Vergleich zu','与……相比','Im Vergleich zum Vorjahr sind die Kosten gesunken.','图表'],
['die Ursache','原因','Die Ursachen für diese Entwicklung sind vielfältig.','书面语'],
['die Folge','后果','Eine mögliche Folge ist ein höherer Energieverbrauch.','书面语'],
['die Lösung','解决办法','Für dieses Problem gibt es mehrere mögliche Lösungen.','讨论'],
['der Vorteil','优点','Ein großer Vorteil ist die zeitliche Flexibilität.','讨论'],
['der Nachteil','缺点','Ein möglicher Nachteil sind die höheren Kosten.','讨论'],
['abhängen von','取决于','Der Erfolg hängt von verschiedenen Faktoren ab.','讨论'],
['die Erfahrung','经验','Praktische Erfahrung ist für den Berufseinstieg hilfreich.','职场'],
['die Leistung','表现，成绩','Ausreichender Schlaf verbessert die Leistung.','校园'],
['fördern','促进，支持','Das Projekt fördert den internationalen Austausch.','书面语'],
['vermeiden','避免','Man sollte unnötige Fehler möglichst vermeiden.','书面语'],
['erhöhen','提高，增加','Diese Regelung soll die Sicherheit erhöhen.','书面语'],
['senken','降低','Neue Technik kann die Betriebskosten senken.','图表'],
['die Nachfrage','需求','Die Nachfrage nach Wohnraum ist stark gestiegen.','图表'],
['das Angebot','供给；提议','Das Angebot an Sprachkursen wird erweitert.','校园'],
['der Durchschnitt','平均值','Der Durchschnitt liegt bei etwa 40 Prozent.','图表'],
['die Bedingung','条件','Unter diesen Bedingungen ist eine genaue Planung besonders wichtig.','书面语'],
['die Auswirkung','影响，后果','Die Auswirkungen des Klimawandels sind bereits sichtbar.','讨论'],
['der Einfluss','影响','Soziale Medien haben großen Einfluss auf den Alltag vieler Menschen.','讨论'],
['die Veränderung','变化','Die Grafik zeigt deutliche Veränderungen seit 2010.','图表'],
['der Fortschritt','进步，进展','Technischer Fortschritt kann viele Arbeitsprozesse erleichtern.','科技'],
['die Verbesserung','改善，提高','Die Maßnahme führte zu einer deutlichen Verbesserung der Qualität.','书面语'],
['die Verschlechterung','恶化','Eine Verschlechterung der Bedingungen sollte vermieden werden.','书面语'],
['die Tendenz','趋势','Insgesamt ist eine steigende Tendenz zu erkennen.','图表'],
['die Mehrheit','多数','Die Mehrheit der Befragten unterstützt den Vorschlag.','图表'],
['die Minderheit','少数','Nur eine Minderheit nutzt dieses Angebot regelmäßig.','图表'],
['der Zeitraum','时间段','Die Daten beziehen sich auf einen Zeitraum von zehn Jahren.','图表'],
['der Wert','数值，价值','Der höchste Wert wurde im Jahr 2025 erreicht.','图表'],
['die Angabe','数据，说明','Die Angaben stammen aus einer aktuellen Studie.','图表'],
['die Statistik','统计数据','Die Statistik verdeutlicht einen langfristigen Wandel.','图表'],
['die Erhebung','调查，数据采集','Die Erhebung wurde an mehreren Hochschulen durchgeführt.','学术'],
['die Umfrage','调查','Laut einer Umfrage wünschen sich viele Studierende mehr Flexibilität.','图表'],
['der Befragte / die Befragte','受访者','Mehr als die Hälfte der Befragten arbeitet neben dem Studium.','图表'],
['die Grafik','图表','Die Grafik stellt die Entwicklung der Studierendenzahlen dar.','图表'],
['darstellen','展示，描述','Das Diagramm stellt die Ergebnisse übersichtlich dar.','图表'],
['verdeutlichen','清楚说明','Die Zahlen verdeutlichen den Unterschied zwischen den Gruppen.','图表'],
['hervorheben','强调，突出','Besonders hervorzuheben ist der starke Anstieg im letzten Jahr.','书面语'],
['betragen','为，达到（数值）','Der Anteil beträgt derzeit rund 35 Prozent.','图表'],
['sich belaufen auf','总计为','Die jährlichen Kosten belaufen sich auf etwa 500 Euro.','图表'],
['steigen','上升','Die Zahl der Teilnehmenden ist deutlich gestiegen.','图表'],
['sinken','下降','Seit 2020 sinkt der Energieverbrauch kontinuierlich.','图表'],
['schwanken','波动','Die Werte schwanken zwischen 20 und 30 Prozent.','图表'],
['sich verdoppeln','翻倍','Die Zahl der Nutzer hat sich innerhalb von fünf Jahren verdoppelt.','图表'],
['sich halbieren','减半','Der Verbrauch hat sich im Vergleich zu früher fast halbiert.','图表'],
['unverändert bleiben','保持不变','Der Anteil blieb über mehrere Jahre nahezu unverändert.','图表'],
['deutlich','明显地','Die Kosten sind im letzten Jahr deutlich gestiegen.','图表'],
['geringfügig','轻微地','Der Wert nahm nur geringfügig zu.','图表'],
['allmählich','逐渐地','Die Situation verbessert sich allmählich.','书面语'],
['erheblich','显著地，大幅地','Die Nachfrage ist in kurzer Zeit erheblich gestiegen.','图表'],
['durchschnittlich','平均地','Studierende lernen durchschnittlich zwei Stunden pro Tag.','图表'],
['insgesamt','总的来说，总计','Insgesamt lässt sich eine positive Entwicklung erkennen.','书面语'],
['im Gegensatz zu','与……相反','Im Gegensatz zu jüngeren Befragten bevorzugen Ältere gedruckte Medien.','讨论'],
['im Laufe von','在……期间','Im Laufe des Studiums sammeln viele praktische Erfahrungen.','书面语'],
['innerhalb','在……之内','Innerhalb eines Jahres stieg der Anteil um zehn Prozentpunkte.','图表'],
['gegenüber','与……相比','Gegenüber dem Vorjahr ist ein leichter Rückgang zu erkennen.','图表'],
['einerseits … andererseits','一方面……另一方面','Einerseits spart Homeoffice Zeit, andererseits fehlt oft der direkte Austausch.','讨论'],
['dennoch','尽管如此','Die Kosten sind hoch; dennoch wird das Angebot gut genutzt.','书面语'],
['hingegen','相反，而','Die erste Gruppe wächst, die zweite hingegen wird kleiner.','书面语'],
['außerdem','此外','Außerdem sollte die soziale Wirkung berücksichtigt werden.','书面语'],
['darüber hinaus','除此之外','Darüber hinaus bietet die Hochschule kostenlose Beratung an.','书面语'],
['folglich','因此','Die Nachfrage steigt; folglich werden mehr Wohnungen benötigt.','书面语'],
['demnach','因此，据此','Demnach ist eine langfristige Lösung erforderlich.','书面语'],
['insofern','就此而言，因此','Insofern erscheint der Vorschlag sinnvoll.','书面语'],
['zwar … aber','虽然……但是','Das Verfahren ist zwar teuer, aber sehr zuverlässig.','讨论'],
['das Argument','论点','Für diese Position gibt es mehrere überzeugende Argumente.','写作'],
['die Behauptung','主张，断言','Diese Behauptung lässt sich mit den Daten nicht eindeutig belegen.','写作'],
['die Begründung','理由，论证','Eine klare Begründung macht den Text überzeugender.','写作'],
['die Stellungnahme','观点陈述','In der Stellungnahme sollte man die eigene Position begründen.','写作'],
['die Einschätzung','评估，看法','Nach meiner Einschätzung überwiegen die Vorteile.','写作'],
['die Sichtweise','观点，视角','Aus wirtschaftlicher Sichtweise ist die Lösung attraktiv.','讨论'],
['die Perspektive','视角，前景','Das Problem sollte aus verschiedenen Perspektiven betrachtet werden.','讨论'],
['der Aspekt','方面','Ein wichtiger Aspekt ist die finanzielle Belastung.','写作'],
['die These','论点，命题','Die These wird im folgenden Abschnitt näher erläutert.','写作'],
['die Schlussfolgerung','结论','Aus den Ergebnissen lässt sich eine klare Schlussfolgerung ziehen.','写作'],
['begründen','说明理由，论证','Bitte begründen Sie Ihre Meinung mit einem Beispiel.','写作'],
['beurteilen','判断，评价','Die Folgen lassen sich noch nicht abschließend beurteilen.','写作'],
['bewerten','评价','Die Ergebnisse müssen sorgfältig bewertet werden.','学术'],
['zustimmen','同意','Viele Studierende stimmen dieser Aussage zu.','讨论'],
['widersprechen','反驳，不同意','Einige Forschungsergebnisse widersprechen dieser Annahme.','讨论'],
['überzeugen','说服','Das Argument konnte viele Teilnehmende überzeugen.','讨论'],
['behaupten','声称','Man kann nicht pauschal behaupten, dass Online-Unterricht schlechter ist.','写作'],
['erläutern','解释，阐述','Die Autorin erläutert die wichtigsten Ursachen der Entwicklung.','写作'],
['erörtern','讨论，论述','Im Text werden Vor- und Nachteile ausführlich erörtert.','写作'],
['abwägen','权衡','Vor einer Entscheidung sollte man Chancen und Risiken abwägen.','写作'],
['voraussetzen','以……为前提','Ein erfolgreiches Studium setzt gute Selbstorganisation voraus.','校园'],
['befürworten','赞成，支持','Viele Fachleute befürworten strengere Umweltstandards.','讨论'],
['ablehnen','拒绝，反对','Ein Teil der Befragten lehnt die Maßnahme ab.','讨论'],
['kritisch betrachten','批判性看待','Die Ergebnisse sollten kritisch betrachtet werden.','学术'],
['in Betracht ziehen','考虑','Auch alternative Lösungen sollten in Betracht gezogen werden.','书面语'],
['zur Verfügung stehen','可供使用','Den Studierenden stehen mehrere Lernräume zur Verfügung.','校园'],
['zur Verfügung stellen','提供','Die Universität stellt zusätzliche Arbeitsplätze zur Verfügung.','校园'],
['eine Rolle spielen','发挥作用','Finanzielle Faktoren spielen bei der Entscheidung eine wichtige Rolle.','写作'],
['in Frage kommen','可考虑，符合条件','Für das Projekt kommen mehrere Standorte in Frage.','书面语'],
['von Bedeutung sein','具有重要意义','Für den Studienerfolg ist regelmäßiges Lernen von großer Bedeutung.','书面语'],
['die Bildung','教育','Bildung hat einen großen Einfluss auf gesellschaftliche Chancen.','校园'],
['die Ausbildung','职业培训','Eine gute Ausbildung verbessert häufig die Berufschancen.','职场'],
['die Weiterbildung','继续教育，进修','Viele Beschäftigte nehmen regelmäßig an Weiterbildungen teil.','职场'],
['der Studiengang','专业，课程项目','Der Studiengang verbindet technische und wirtschaftliche Inhalte.','校园'],
['die Hochschule','高校','Die Hochschule bietet zahlreiche internationale Programme an.','校园'],
['die Vorlesung','大学讲座课','Die Vorlesung findet jeden Dienstag statt.','校园'],
['das Seminar','研讨课','Im Seminar diskutieren die Studierenden aktuelle Forschungsthemen.','校园'],
['die Prüfung','考试','Für die Prüfung ist eine rechtzeitige Vorbereitung wichtig.','校园'],
['die Zulassung','录取，准入','Für die Zulassung müssen bestimmte Voraussetzungen erfüllt sein.','校园'],
['die Bewerbung','申请','Die Bewerbung muss vollständig und fristgerecht eingereicht werden.','校园'],
['die Einschreibung','注册入学','Nach der Zulassung folgt die Einschreibung an der Hochschule.','校园'],
['der Abschluss','毕业，学位','Ein Hochschulabschluss kann die Berufschancen verbessern.','校园'],
['die Qualifikation','资格，资质','Für diese Stelle ist eine technische Qualifikation erforderlich.','职场'],
['die Kompetenz','能力，胜任力','Digitale Kompetenzen werden in vielen Berufen wichtiger.','职场'],
['die Betreuung','指导，照顾','Eine gute Betreuung ist besonders zu Beginn des Studiums hilfreich.','校园'],
['die Beratung','咨询，指导','Die Studienberatung unterstützt bei Fragen zur Kurswahl.','校园'],
['die Teilnahme','参加','Die Teilnahme an der Veranstaltung ist kostenlos.','校园'],
['die Anwesenheit','出席','In manchen Seminaren ist regelmäßige Anwesenheit erforderlich.','校园'],
['die Frist','期限','Die Frist für die Abgabe endet am Freitag.','校园'],
['die Abgabe','提交','Die Abgabe der Hausarbeit erfolgt online.','校园'],
['die Quelle','来源，资料来源','Alle verwendeten Quellen müssen angegeben werden.','学术'],
['die Literatur','文献','Für die Hausarbeit sollte aktuelle Literatur verwendet werden.','学术'],
['die Veröffentlichung','出版物，发表','Die Veröffentlichung enthält neue Forschungsergebnisse.','学术'],
['die Wissenschaft','科学，学术','Wissenschaft lebt von überprüfbaren Ergebnissen und Diskussion.','学术'],
['wissenschaftlich','科学的，学术的','Die Aussage muss wissenschaftlich begründet werden.','学术'],
['untersuchen','研究，调查','Die Studie untersucht das Lernverhalten von Studierenden.','学术'],
['analysieren','分析','Die Daten werden anschließend statistisch analysiert.','学术'],
['auswerten','评估，分析数据','Nach der Umfrage werden die Antworten ausgewertet.','学术'],
['nachweisen','证明，证实','Ein direkter Zusammenhang konnte nicht eindeutig nachgewiesen werden.','学术'],
['belegen','证实；引用证明','Die These lässt sich durch mehrere Studien belegen.','学术'],
['feststellen','确定，发现','Die Forschenden stellten deutliche Unterschiede fest.','学术'],
['beobachten','观察','Diese Entwicklung lässt sich seit mehreren Jahren beobachten.','学术'],
['erfassen','记录，采集','In der Studie werden Alter und Bildungsstand erfasst.','学术'],
['vergleichen','比较','Die Untersuchung vergleicht zwei unterschiedliche Lernmethoden.','学术'],
['unterscheiden','区分','Man muss zwischen Ursache und Folge unterscheiden.','学术'],
['einordnen','归类，置于背景中理解','Die Ergebnisse lassen sich in einen größeren Zusammenhang einordnen.','学术'],
['zusammenfassen','总结','Am Ende werden die wichtigsten Ergebnisse kurz zusammengefasst.','写作'],
['zitieren','引用','Wörtliche Aussagen müssen korrekt zitiert werden.','学术'],
['recherchieren','检索，调查资料','Für die Präsentation müssen zuverlässige Quellen recherchiert werden.','学术'],
['dokumentieren','记录，形成文档','Alle Arbeitsschritte werden sorgfältig dokumentiert.','学术'],
['die Umwelt','环境','Der Schutz der Umwelt betrifft die gesamte Gesellschaft.','环保'],
['der Klimawandel','气候变化','Der Klimawandel stellt Städte vor neue Herausforderungen.','环保'],
['der Klimaschutz','气候保护','Beim Klimaschutz spielen erneuerbare Energien eine wichtige Rolle.','环保'],
['die Nachhaltigkeit','可持续性','Nachhaltigkeit gewinnt in Unternehmen zunehmend an Bedeutung.','环保'],
['die Ressource','资源','Wasser ist eine lebenswichtige und begrenzte Ressource.','环保'],
['der Energieverbrauch','能源消耗','Der Energieverbrauch von Gebäuden soll deutlich sinken.','环保'],
['die Energieeffizienz','能源效率','Eine bessere Dämmung erhöht die Energieeffizienz.','环保'],
['die erneuerbare Energie','可再生能源','Erneuerbare Energien sollen fossile Energieträger zunehmend ersetzen.','环保'],
['die Emission','排放','Neue Technik kann schädliche Emissionen reduzieren.','环保'],
['der CO₂-Ausstoß','二氧化碳排放','Der CO₂-Ausstoß des Verkehrs ist weiterhin hoch.','环保'],
['die Belastung','负担；污染','Lärm kann für Anwohner eine erhebliche Belastung sein.','环保'],
['die Verschmutzung','污染','Die Verschmutzung von Flüssen hat langfristige Folgen.','环保'],
['der Abfall','垃圾，废弃物','Durch Wiederverwendung lässt sich Abfall vermeiden.','环保'],
['das Recycling','回收利用','Recycling spart Rohstoffe und reduziert Abfall.','环保'],
['der Rohstoff','原材料','Viele technische Produkte benötigen seltene Rohstoffe.','环保'],
['der Wasserverbrauch','用水量','Der Wasserverbrauch lässt sich durch effiziente Technik senken.','环保'],
['die Versorgung','供应，保障','Eine sichere Energieversorgung ist für die Wirtschaft wichtig.','环保'],
['die Entsorgung','处理，废弃物处置','Für Batterien gelten besondere Regeln zur Entsorgung.','环保'],
['einsparen','节省','Mit moderner Technik lässt sich viel Energie einsparen.','环保'],
['verbrauchen','消耗','Alte Geräte verbrauchen häufig mehr Strom.','环保'],
['schützen','保护','Natürliche Lebensräume müssen besser geschützt werden.','环保'],
['belasten','给……造成负担，污染','Hohe Emissionen belasten Umwelt und Gesundheit.','环保'],
['reduzieren','减少','Das Unternehmen möchte seinen Energieverbrauch reduzieren.','环保'],
['wiederverwenden','重复使用','Viele Materialien können mehrfach wiederverwendet werden.','环保'],
['umweltfreundlich','环保的','Öffentliche Verkehrsmittel gelten als vergleichsweise umweltfreundlich.','环保'],
['energieeffizient','节能高效的','Neue Gebäude sollen möglichst energieeffizient geplant werden.','环保'],
['ressourcenschonend','节约资源的','Eine ressourcenschonende Produktion wird immer wichtiger.','环保'],
['langfristig','长期地','Langfristig können Investitionen in Effizienz Kosten sparen.','书面语'],
['die Digitalisierung','数字化','Die Digitalisierung verändert Studium und Arbeitswelt.','科技'],
['die Technologie','技术','Neue Technologien eröffnen zusätzliche Möglichkeiten.','科技'],
['die Innovation','创新','Innovationen können zur Lösung gesellschaftlicher Probleme beitragen.','科技'],
['die künstliche Intelligenz','人工智能','Künstliche Intelligenz wird bereits in vielen Bereichen eingesetzt.','科技'],
['die Automatisierung','自动化','Automatisierung verändert zahlreiche Tätigkeiten.','科技'],
['die Anwendung','应用，应用程序','Die Anwendung erleichtert den Zugriff auf Lernmaterialien.','科技'],
['das Verfahren','方法，流程','Das neue Verfahren ist schneller und energieeffizienter.','科技'],
['die Methode','方法','Die Methode eignet sich besonders für kleine Gruppen.','学术'],
['das Gerät','设备','Das Gerät misst Temperatur und Luftfeuchtigkeit.','科技'],
['das System','系统','Das System verarbeitet große Datenmengen automatisch.','科技'],
['die Daten','数据','Persönliche Daten müssen zuverlässig geschützt werden.','科技'],
['der Datenschutz','数据保护','Beim Einsatz digitaler Dienste ist Datenschutz besonders wichtig.','科技'],
['die Sicherheit','安全','Die Sicherheit der Nutzerdaten hat hohe Priorität.','科技'],
['das Netzwerk','网络','Über das Netzwerk können mehrere Geräte miteinander kommunizieren.','科技'],
['der Zugang','访问，准入','Studierende erhalten kostenlosen Zugang zur Datenbank.','校园'],
['die Nutzung','使用','Die Nutzung digitaler Angebote nimmt weiter zu.','科技'],
['die Verfügbarkeit','可用性','Die Verfügbarkeit von Informationen ist deutlich gestiegen.','科技'],
['die Infrastruktur','基础设施','Eine leistungsfähige digitale Infrastruktur ist zunehmend wichtig.','科技'],
['die Forschungsergebnisse','研究成果','Die Forschungsergebnisse wurden auf einer Konferenz vorgestellt.','学术'],
['entwickeln','开发，发展','Das Team entwickelt eine neue Lernplattform.','科技'],
['anwenden','应用','Die Methode lässt sich in verschiedenen Bereichen anwenden.','学术'],
['einsetzen','使用，投入','Viele Unternehmen setzen bereits automatische Systeme ein.','科技'],
['speichern','存储','Die Daten werden verschlüsselt gespeichert.','科技'],
['verarbeiten','处理','Das Programm kann große Datenmengen schnell verarbeiten.','科技'],
['übertragen','传输','Die Messwerte werden automatisch an den Server übertragen.','科技'],
['ersetzen','替代','Digitale Dokumente ersetzen zunehmend Papierformulare.','科技'],
['vereinfachen','简化','Online-Dienste können Verwaltungsprozesse vereinfachen.','科技'],
['beschleunigen','加快','Automatisierung kann bestimmte Abläufe deutlich beschleunigen.','科技'],
['zuverlässig','可靠的','Die Ergebnisse müssen zuverlässig und nachvollziehbar sein.','书面语'],
['effizient','高效的','Eine gute Organisation hilft, effizienter zu arbeiten.','书面语'],
['der Arbeitsplatz','工作岗位；工作场所','Flexible Arbeitsplätze werden in vielen Unternehmen häufiger.','职场'],
['der Arbeitgeber','雇主','Arbeitgeber müssen für sichere Arbeitsbedingungen sorgen.','职场'],
['der Arbeitnehmer / die Arbeitnehmerin','雇员','Arbeitnehmer wünschen sich häufig flexible Arbeitszeiten.','职场'],
['die Arbeitszeit','工作时间','Flexible Arbeitszeiten können die Vereinbarkeit verbessern.','职场'],
['die Arbeitsbedingungen','工作条件','Gute Arbeitsbedingungen erhöhen oft die Zufriedenheit.','职场'],
['die Beschäftigung','就业','Die Beschäftigung in der Branche ist deutlich gestiegen.','职场'],
['die Arbeitslosigkeit','失业','Eine gute Ausbildung kann das Risiko von Arbeitslosigkeit verringern.','社会'],
['das Einkommen','收入','Das durchschnittliche Einkommen unterscheidet sich nach Region.','经济'],
['das Gehalt','工资，薪资','Das Gehalt ist nur ein Faktor bei der Berufswahl.','职场'],
['die Karriere','职业生涯','Weiterbildung kann für die berufliche Karriere wichtig sein.','职场'],
['die Berufserfahrung','工作经验','Viele Stellen setzen bereits erste Berufserfahrung voraus.','职场'],
['die Verantwortung','责任','Führungskräfte tragen Verantwortung für ihr Team.','职场'],
['die Aufgabe','任务','Zu meinen Aufgaben gehört die Prüfung technischer Unterlagen.','职场'],
['die Tätigkeit','工作内容，活动','Die Tätigkeit erfordert technisches Verständnis und Teamarbeit.','职场'],
['die Zusammenarbeit','合作','Eine gute Zusammenarbeit erleichtert komplexe Projekte.','职场'],
['die Teamarbeit','团队合作','Teamarbeit ist in internationalen Projekten besonders wichtig.','职场'],
['die Führungskraft','管理人员','Die Führungskraft gibt regelmäßig Rückmeldung.','职场'],
['die Vereinbarkeit','兼顾，相容性','Homeoffice kann die Vereinbarkeit von Beruf und Familie verbessern.','职场'],
['flexibel','灵活的','Viele Beschäftigte wünschen sich flexible Arbeitsmodelle.','职场'],
['selbstständig','独立地，自主地','Studierende müssen viele Aufgaben selbstständig organisieren.','校园'],
['verantwortlich','负责的','Sie ist für die technische Planung verantwortlich.','职场'],
['beruflich','职业上的','Berufliche Erfahrungen können das Studium sinnvoll ergänzen.','职场'],
['sich bewerben um','申请……','Viele Absolventen bewerben sich um internationale Stellen.','职场'],
['einstellen','雇用；设置','Das Unternehmen möchte im kommenden Jahr neue Mitarbeitende einstellen.','职场'],
['kündigen','辞职；解约','Beschäftigte können ihren Vertrag unter bestimmten Bedingungen kündigen.','职场'],
['beschäftigen','雇用；使忙于','Das Unternehmen beschäftigt mehr als tausend Mitarbeitende.','职场'],
['verdienen','赚取','Berufserfahrung kann helfen, später mehr zu verdienen.','职场'],
['zusammenarbeiten','合作','Mehrere Fachbereiche arbeiten eng zusammen.','职场'],
['übernehmen','承担，接手','Nach der Einarbeitung übernimmt sie mehr Verantwortung.','职场'],
['die Wirtschaft','经济','Die Wirtschaft ist auf gut ausgebildete Fachkräfte angewiesen.','经济'],
['das Unternehmen','企业','Das Unternehmen investiert stark in nachhaltige Technologien.','经济'],
['der Betrieb','企业；运营','Der Betrieb der Anlage verursacht laufende Kosten.','经济'],
['die Branche','行业','Die Baubranche steht vor großen Veränderungen.','经济'],
['der Markt','市场','Auf dem Markt gibt es inzwischen viele ähnliche Angebote.','经济'],
['der Wettbewerb','竞争','Starker Wettbewerb kann Innovationen fördern.','经济'],
['die Kosten','成本，费用','Die Kosten sollten bereits bei der Planung berücksichtigt werden.','经济'],
['der Preis','价格','Der Preis allein sagt wenig über die Qualität aus.','经济'],
['der Umsatz','营业额','Der Umsatz des Unternehmens ist im letzten Jahr gestiegen.','经济'],
['der Gewinn','利润','Ein hoher Umsatz führt nicht automatisch zu einem hohen Gewinn.','经济'],
['der Verlust','亏损，损失','Das Unternehmen konnte den Verlust deutlich verringern.','经济'],
['die Investition','投资','Die Investition in neue Technik soll sich langfristig lohnen.','经济'],
['der Konsum','消费','Nachhaltiger Konsum gewinnt für viele Menschen an Bedeutung.','社会'],
['der Verbraucher / die Verbraucherin','消费者','Verbraucher achten zunehmend auf Energieeffizienz.','经济'],
['das Produkt','产品','Das Produkt soll langlebig und reparierbar sein.','经济'],
['die Dienstleistung','服务','Digitale Dienstleistungen werden immer häufiger genutzt.','经济'],
['die Produktion','生产','Die Produktion soll klimafreundlicher gestaltet werden.','经济'],
['die Finanzierung','融资，资金安排','Die Finanzierung des Projekts ist noch nicht vollständig geklärt.','经济'],
['wirtschaftlich','经济的；经济上可行的','Die Lösung muss technisch sinnvoll und wirtschaftlich sein.','经济'],
['investieren','投资','Viele Unternehmen investieren in erneuerbare Energien.','经济'],
['produzieren','生产','Die Anlage produziert Strom aus Sonnenenergie.','经济'],
['anbieten','提供','Die Hochschule bietet zusätzliche Sprachkurse an.','校园'],
['nachfragen','询问；需求','Bei Unklarheiten sollte man rechtzeitig nachfragen.','校园'],
['sich leisten','负担得起','Nicht alle Studierenden können sich eine hohe Miete leisten.','社会'],
['wachsen','增长','Die Nachfrage nach Fachkräften wächst weiter.','经济'],
['zurückgehen','下降，减少','Die Zahl der Bewerbungen ist leicht zurückgegangen.','图表'],
['die Bevölkerung','人口','Die Bevölkerung in Großstädten wächst in vielen Regionen.','社会'],
['die Migration','迁移，移民','Migration beeinflusst Arbeitsmarkt und Gesellschaft.','社会'],
['die Integration','融入，融合','Sprache spielt für eine gelungene Integration eine wichtige Rolle.','社会'],
['die Chancengleichheit','机会平等','Bildung soll zu mehr Chancengleichheit beitragen.','社会'],
['die Ungleichheit','不平等','Soziale Ungleichheit kann Bildungschancen beeinflussen.','社会'],
['die Armut','贫困','Armut wirkt sich auf viele Lebensbereiche aus.','社会'],
['der Wohlstand','富裕，繁荣','Wirtschaftliches Wachstum führt nicht automatisch zu mehr Wohlstand für alle.','社会'],
['die Gesundheit','健康','Ausreichende Bewegung wirkt sich positiv auf die Gesundheit aus.','健康'],
['die Ernährung','饮食，营养','Eine ausgewogene Ernährung kann die Leistungsfähigkeit unterstützen.','健康'],
['die Bewegung','运动，活动','Regelmäßige Bewegung ist ein wichtiger Ausgleich zum Sitzen.','健康'],
['der Verkehr','交通','Der Verkehr verursacht einen großen Teil der städtischen Emissionen.','社会'],
['der Wohnraum','住房空间','Bezahlbarer Wohnraum ist in vielen Städten knapp.','社会'],
['die Miete','房租','Die Mieten sind in vielen Großstädten stark gestiegen.','社会'],
['die Stadtentwicklung','城市发展','Nachhaltige Stadtentwicklung berücksichtigt Wohnen, Verkehr und Klima.','社会'],
['die Lebensqualität','生活质量','Grünflächen können die Lebensqualität in Städten erhöhen.','社会'],
['die Freizeit','空闲时间','Viele Studierende müssen Lernen, Arbeit und Freizeit miteinander verbinden.','社会'],
['die Medien','媒体','Medien beeinflussen, welche Themen öffentlich diskutiert werden.','社会'],
['die Kommunikation','交流，沟通','Klare Kommunikation ist für erfolgreiche Teamarbeit entscheidend.','职场'],
['die Information','信息','Zuverlässige Informationen sollten leicht zugänglich sein.','社会'],
['die Öffentlichkeit','公众','Das Thema wird in der Öffentlichkeit kontrovers diskutiert.','社会'],
['gesellschaftlich','社会的','Die Digitalisierung hat weitreichende gesellschaftliche Folgen.','社会'],
['beeinflussen','影响','Viele Faktoren beeinflussen die Entscheidung für einen Studienort.','讨论']
];
window.COZY_WORDS = rows.map((row,index)=>({id:'w'+String(index+1).padStart(4,'0'),w:row[0],m:row[1],ex:row[2],topic:row[3]}));
})();
